[package]
name = "tui"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
crossterm.workspace = true
memmap2.workspace = true
ratatui.workspace = true
similar.workspace = true
strum.workspace = true
supports-color.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
portable-pty.workspace = true
tempfile.workspace = true
test-case.workspace = true
