[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm.workspace = true
memmap2 = "0.9"
ratatui = { version = "0.29", default-features = false, features = [
  "crossterm",
] }
similar = "2"
strum.workspace = true

[dev-dependencies]
tempfile.workspace = true
test-case.workspace = true
