[package]
name = "dotrift"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["tui", "templater", "demo"]

[features]
testing = []

[dependencies]
tui = { path = "./tui" }
templater = { path = "./templater" }
clap = { version = "4.6.0", features = ["derive"] }
crossterm.workspace = true
dirs = "6.0.0"
glob = "0.3.3"
ignore = "0.4.25"
indexmap = { version = "2.14.0", features = ["serde"] }
miette.workspace = true
normalize-path = "0.2.1"
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde.workspace = true
strum.workspace = true
toml.workspace = true
twox-hash = "2.1.2"
libc = "0.2.184"

[dev-dependencies]
dotrift = { path = ".", features = ["testing"] }
proptest.workspace = true
insta.workspace = true
tempfile.workspace = true
test-case.workspace = true

[workspace.dependencies]
criterion = { version = "0.8.2", default-features = false, features = [
  "cargo_bench_support",
] }
crossterm = { version = "0.29.0", default-features = false, features = [
  "events",
] }
insta = { version = "1.48.0", features = ["filters"] }
memmap2 = "0.9.10"
miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
supports-color = "3.0.2"
tempfile = "3.27.0"
proptest = "1.11.0"
rand = "0.9.4"
test-case = "3.3.1"
toml = "1.1.2"
thiserror = "2.0.18"
portable-pty = "0.9.0"
