[package]
name = "templater"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
memmap2.workspace = true
miette.workspace = true
thiserror.workspace = true

[features]
testing = []

[dev-dependencies]
templater = { path = ".", features = ["testing"] }
proptest.workspace = true
test-case.workspace = true
tempfile.workspace = true
insta.workspace = true
