mod common;

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use common::TestEnv;
use dotrift::commands::apply::run;
use dotrift::config::DeployType;
use dotrift::state::{Kind, StateDatabase, StateRecord};
use proptest::prelude::*;

const MAX_ENTRIES: usize = 8;

#[derive(Debug, Clone)]
struct Entry {
    target: PathBuf,
    deploy_type: DeployType,
    mode: Option<u32>,
    content: Vec<u8>,
}

fn component() -> impl Strategy<Value = String> {
    (b'a'..=b'z').prop_map(|byte| (byte as char).to_string())
}

fn target_path() -> impl Strategy<Value = PathBuf> {
    prop::collection::vec(component(), 1..=3)
        .prop_map(|components: Vec<String>| components.into_iter().collect())
}

fn deploy_type() -> impl Strategy<Value = DeployType> {
    prop_oneof![
        Just(DeployType::Symlink),
        Just(DeployType::Copy),
        Just(DeployType::Template),
    ]
}

// Template content must render without error: byte payloads free of `{` and
// `}` contain no tag delimiters, so the engine renders them verbatim.
//
// Rejecting braces per generated byte (0.78% of u8 values) keeps shrinking
// intact, unlike a `prop_filter` over the whole buffer which would reject most
// samples and exhaust the retry budget. Same approach as
// `templater/tests/property.rs::brace_free_bytes`.
fn brace_free_bytes() -> BoxedStrategy<Vec<u8>> {
    let byte = any::<u8>().prop_filter("exclude '{' and '}'", |b| *b != b'{' && *b != b'}');
    prop::collection::vec(byte, 0..=64).boxed()
}

fn content(deploy_type: DeployType) -> impl Strategy<Value = Vec<u8>> {
    match deploy_type {
        DeployType::Template => brace_free_bytes(),
        DeployType::Symlink | DeployType::Copy => {
            prop::collection::vec(any::<u8>(), 0..=64).boxed()
        }
    }
}

// `mode` only applies to copy and template entries; with `symlink` it is a
// configuration error.
fn mode(deploy_type: DeployType) -> impl Strategy<Value = Option<u32>> {
    match deploy_type {
        DeployType::Symlink => Just(None).boxed(),
        DeployType::Copy | DeployType::Template => prop_oneof![
            Just(None),
            Just(Some(0o600)),
            Just(Some(0o644)),
            Just(Some(0o755)),
        ]
        .boxed(),
    }
}

fn entry() -> impl Strategy<Value = Entry> {
    (target_path(), deploy_type())
        .prop_flat_map(|(target, deploy_type)| {
            (
                Just(target),
                Just(deploy_type),
                content(deploy_type),
                mode(deploy_type),
            )
        })
        .prop_map(|(target, deploy_type, content, mode)| Entry {
            target,
            deploy_type,
            mode,
            content,
        })
}

fn valid_targets(entries: &[Entry]) -> bool {
    for (index, left) in entries.iter().enumerate() {
        for right in &entries[index + 1..] {
            if left.target == right.target
                || left.target.starts_with(&right.target)
                || right.target.starts_with(&left.target)
            {
                return false;
            }
        }
    }
    true
}

fn deployment() -> impl Strategy<Value = Vec<Entry>> {
    prop::collection::vec(entry(), 0..=MAX_ENTRIES)
        .prop_filter("targets must be distinct and non-ancestor", |entries| {
            valid_targets(entries)
        })
}

fn write_source(env: &TestEnv, entries: &[Entry]) {
    let source = env.path("source");
    fs::create_dir_all(&source).expect("cannot create source dir");
    for (index, entry) in entries.iter().enumerate() {
        fs::write(source.join(format!("s{index}")), &entry.content).expect("cannot write source");
    }
    let mut toml = String::from("[portal]\n");
    for (index, entry) in entries.iter().enumerate() {
        toml.push_str(&format!(
            "{:?} = {:?}\n",
            format!("s{index}"),
            entry.target.to_string_lossy()
        ));
    }
    if entries
        .iter()
        .any(|entry| entry.deploy_type != DeployType::Symlink)
    {
        toml.push_str("[rule]\n");
        for entry in entries {
            if entry.deploy_type == DeployType::Symlink {
                continue;
            }
            let mut rule = match entry.deploy_type {
                DeployType::Copy => "type = \"copy\"".to_string(),
                DeployType::Template => "type = \"template\"".to_string(),
                DeployType::Symlink => unreachable!(),
            };
            if let Some(mode) = entry.mode {
                rule.push_str(&format!(", mode = \"{mode:o}\""));
            }
            toml.push_str(&format!(
                "{:?} = {{ {rule} }}\n",
                entry.target.to_string_lossy()
            ));
        }
    }
    fs::write(source.join("dotrift.toml"), toml).expect("cannot write dotrift.toml");
}

#[derive(Debug, PartialEq, Eq)]
enum Node {
    Dir,
    File { bytes: Vec<u8>, mode: u32 },
    Symlink(PathBuf),
}

fn target_snapshot(root: &Path) -> BTreeMap<PathBuf, Node> {
    let mut snapshot = BTreeMap::new();
    if fs::symlink_metadata(root).is_ok_and(|metadata| metadata.file_type().is_dir()) {
        collect_snapshot(root, root, &mut snapshot);
    }
    snapshot
}

fn collect_snapshot(base: &Path, current: &Path, snapshot: &mut BTreeMap<PathBuf, Node>) {
    for entry in fs::read_dir(current).expect("cannot read target directory") {
        let path = entry.expect("cannot read directory entry").path();
        let relative = path
            .strip_prefix(base)
            .expect("target path below root")
            .to_path_buf();
        let metadata = fs::symlink_metadata(&path).expect("cannot inspect target path");
        if metadata.file_type().is_dir() {
            snapshot.insert(relative, Node::Dir);
            collect_snapshot(base, &path, snapshot);
        } else if metadata.file_type().is_symlink() {
            snapshot.insert(
                relative,
                Node::Symlink(fs::read_link(&path).expect("cannot read symlink target")),
            );
        } else {
            snapshot.insert(
                relative,
                Node::File {
                    bytes: fs::read(&path).expect("cannot read target file"),
                    mode: metadata.permissions().mode() & 0o777,
                },
            );
        }
    }
}

fn db_snapshot() -> BTreeMap<PathBuf, (Kind, PathBuf, Option<PathBuf>, Option<String>)> {
    StateDatabase::open()
        .expect("cannot open state database")
        .managed_paths()
        .expect("cannot read managed paths")
        .into_iter()
        .map(|record: StateRecord| {
            (
                record.target_path,
                (
                    record.kind,
                    record.source_path,
                    record.link_target,
                    record.content_hash,
                ),
            )
        })
        .collect()
}

proptest! {
    #![proptest_config(proptest::test_runner::Config { cases: 128, ..proptest::test_runner::Config::default() })]

    // Applying a deployment twice converges: the second run finds every target
    // a managed path whose fingerprint still matches, so it replaces them
    // without prompting, leaving the target tree and the state database
    // identical to the first run.
    #[test]
    fn apply_is_idempotent(entries in deployment()) {
        let env = TestEnv::new();
        write_source(&env, &entries);

        let first = run(&env.path("source"), Some(env.path("target"))).unwrap();
        let after_first = (target_snapshot(&env.path("target")), db_snapshot());
        let second = run(&env.path("source"), Some(env.path("target"))).unwrap();
        let after_second = (target_snapshot(&env.path("target")), db_snapshot());

        prop_assert_eq!(first, dotrift::ExitStatus::Success);
        prop_assert_eq!(second, dotrift::ExitStatus::Success);
        prop_assert_eq!(after_first, after_second);
    }
}
